package overhead

type ServiceGroup struct {
	// Code generated by life Begin; DO NOT EDIT.

	OverheadInfoService
	OverheadCategoryService
	OverheadDailyStatisticsService
	OverheadMonthStatisticsService
	// Code generated by life End; DO NOT EDIT.
}
