version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  web:
    image: node:16
    ports:
      - '18080:8080'
    depends_on:
      - server
    working_dir: /web # 如果docker 设置了workdir 则此处不需要设置
    #若网络不太好，请自行换源，如下
    # command: bash -c "yarn config set registry https://registry.npm.taobao.org --global && yarn install && yarn serve"
    # command: bash -c "yarn install && yarn serve"
    tty: true
    stdin_open: true
    volumes:
      - ./web:/web
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    image: golang:1.18
    ports:
      - '18888:8888'
      - '18889:8889'
    depends_on:
      - mysql
      - redis
    volumes:
      - ./server:/server
    working_dir: /server # 如果docker 设置了workdir 则此处不需要设置 
    # command: bash -c "go env -w GOPROXY=https://goproxy.cn,direct && go mod tidy && go run main.go"
    tty: true
    stdin_open: true
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12

  mysql:
    image: mysql:8.0.21 # 如果您是 arm64 架构：如 MacOS 的 M1，请修改镜像为 image: mysql/mysql-server:8.0.21
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    ports:
      - "3306:3306" # host物理直接映射端口为3306
    environment:
      MYSQL_DATABASE: 'kny_cash' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: '123456' # root管理员用户密码
    volumes:
      - ./runtime/mysql:/var/lib/mysql
    tty: true
    stdin_open: true
    networks:
      network:
        ipv4_address: 177.7.0.13

  redis:
    image: redis:6.0.6
    ports:
      - '6379:6379'
    volumes:
      - ./runtime/redis:/data
    networks:
      network:
        ipv4_address: 177.7.0.14
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "../runtime/zookeeper:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "../runtime/kafka:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
