package overhead

type ApiGroup struct {
	// Code generated by life Begin; DO NOT EDIT.

	OverheadInfoApi
	OverheadCategoryApi
	OverheadDailyStatisticsApi
	OverheadMonthStatisticsApi
	// Code generated by life End; DO NOT EDIT.
}
