package overhead

type RouterGroup struct {
	// Code generated by life Begin; DO NOT EDIT.

	OverheadInfoRouter
	OverheadCategoryRouter
	OverheadDailyStatisticsRouter
	OverheadMonthStatisticsRouter
	// Code generated by life End; DO NOT EDIT.
}
